language: node_js
node_js:
  - "4"
sudo: false
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
env:
  - EMBER_TRY_SCENARIO=ember-2.10
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
  - npm install
  - bower install
script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: npm
  email: lawrencejw@gmail.com
  api_key:
    secure: CVvxpiNpUMkYdU5/So+QKqWw4vW+i0apvmB/j9f/1DgzsZMVaGrV5yldpvUqUGrMsONPSDYvqJH17ayqaC+GrsyPukbpUuk8C2bXS9vFOOq5vW3FSqShOz3eHN4V4t7YdW0m/UqtGfZak+JDYxQ/l6Jf9A8zk1fGA7duoUYmSgqp037dXrmf69EOdjpLh9dJ+pZTDsOOyIbAHClNq1hPm6LPOPQsmDvV/1qT9mzcFo1tD0mcc+YzVza/Dlrxf20ccd7+C/Nq7tc1DVGS5UnOoQdWhekEohkBcLk4i/vj+gLU9LkxK8mRtOFgk1hbcWYpwWxtxJnjVh6JzcjRg/z6/l6ztk9sndP/rMLN3Irto/x8OaqkydzuboR+0tHE2q23i4N6N5h9jpUzXM2Se8BMJaNwCjZpM1TDb29ckHgRLzxicXA8go/PSwycILK7A/0fseYXc9JyiBh4PuK6xWRi92A+U27xTSYk38skcCuGHYhXTfZiACpOt8GcH4weKByQ1+7MwlWaLbwMmGrmu/+ImLue3b2/VuXSbo2h05api9hQMq6/7HmE4UUbxBN29nWbaMXjSuTlCu7AFjULBhc5GpabrSQLTvjbmOxuJEuzN7VO5jU5I7HLLBjMqywGxPabseysmVpEJfIAp5kQDcExyhGjM9shCKvs7lFO7iudSII=
  on:
    tags: true
    repo: jwlawrence/ember-tri-state
